name: intern_kassation_app
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.5+1

environment:
  sdk: ^3.10.7

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  flutter_bloc: ^9.1.1
  provider: ^6.1.2

  # Networking
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  retry: ^3.1.2

  # Serialization & mapping
  dart_mappable: ^4.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Functional / FP
  fpdart: ^1.2.0

  # Storage & config
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

  # Routing & navigation
  go_router: ^16.0.0

  # Utilities
  intl: any
  package_info_plus: ^9.0.0
  uuid: ^4.5.2
  mime: ^2.0.0
  path: ^1.9.1

  # Logging
  pretty_dio_logger: ^1.4.0
  logging: ^1.3.0

  # UI & scanning
  mobile_scanner: ^7.1.2
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  
dev_dependencies:
# Flutter test SDKs
  flutter_test:
    sdk: flutter
  # integration_test:
  #  sdk: flutter

  # Testing & assertions
  bloc_test: ^10.0.0
  clock: ^1.1.2
  fake_async: ^1.3.3

  # Lints & mocks
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  bloc_lint: ^0.3.5

  # Code generation & build tools
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.6.3
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/certs/
    - .env.development
    - .env.production
